name = "UnionWrappers"
uuid = "74a707ba-e539-4b25-b122-a64fb4a1bb11"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "0.1.0-DEV"

[deps]

[compat]
julia = "1.6"
ComponentArrays = "0.14, 0.15"
Requires = "1.3"

[extensions]
UnionWrappersComponentArraysExt = "ComponentArrays"

[weakdeps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"

[extras]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

